import pandas as pd
import numpy as np

pd_traing_loss = pd.read_csv( 'H1010/training_loss.csv', header = None, names = ('H'))
pd_traing_loss['H1030'] = pd.read_csv( 'H1030/training_loss.csv',header = None)
pd_traing_loss['H1050'] = pd.read_csv( 'H1050/training_loss.csv',header = None)
pd_traing_loss['H1070'] = pd.read_csv( 'H1070/training_loss.csv',header = None)
pd_traing_loss['H1090'] = pd.read_csv( 'H1090/training_loss.csv',header = None)
pd_traing_loss['H3010'] = pd.read_csv( 'H3010/training_loss.csv',header = None)
pd_traing_loss['H3030'] = pd.read_csv( 'H3030/training_loss.csv',header = None)
pd_traing_loss['H3050'] = pd.read_csv( 'H3050/training_loss.csv',header = None)
pd_traing_loss['H3070'] = pd.read_csv( 'H3070/training_loss.csv',header = None)
pd_traing_loss['H3090'] = pd.read_csv( 'H3090/training_loss.csv',header = None)
pd_traing_loss['H5010'] = pd.read_csv( 'H5010/training_loss.csv',header = None)
pd_traing_loss['H5030'] = pd.read_csv( 'H5030/training_loss.csv',header = None)
pd_traing_loss['H5050'] = pd.read_csv( 'H5050/training_loss.csv',header = None)
pd_traing_loss['H5070'] = pd.read_csv( 'H5070/training_loss.csv',header = None)
pd_traing_loss['H5090'] = pd.read_csv( 'H5090/training_loss.csv',header = None)
pd_traing_loss['H9010'] = pd.read_csv( 'H9010/training_loss.csv',header = None)
pd_traing_loss['H9030'] = pd.read_csv( 'H9030/training_loss.csv',header = None)
pd_traing_loss['H9050'] = pd.read_csv( 'H9050/training_loss.csv',header = None)
pd_traing_loss['H9070'] = pd.read_csv( 'H9070/training_loss.csv',header = None)
pd_traing_loss['H9090'] = pd.read_csv( 'H9090/training_loss.csv',header = None)
#print(pd_traing_loss)
np.savetxt("training_loss_marged.csv", pd_traing_loss.values , delimiter=",")

pd_acuracy = pd.read_csv( 'H1010/acuracy.csv', header = None, names = ('H'))
pd_acuracy['H1030'] = pd.read_csv( 'H1030/acuracy.csv',header = None)
pd_acuracy['H1050'] = pd.read_csv( 'H1050/acuracy.csv',header = None)
pd_acuracy['H1070'] = pd.read_csv( 'H1070/acuracy.csv',header = None)
pd_acuracy['H1090'] = pd.read_csv( 'H1090/acuracy.csv',header = None)
pd_acuracy['H3010'] = pd.read_csv( 'H3010/acuracy.csv',header = None)
pd_acuracy['H3030'] = pd.read_csv( 'H3030/acuracy.csv',header = None)
pd_acuracy['H3050'] = pd.read_csv( 'H3050/acuracy.csv',header = None)
pd_acuracy['H3070'] = pd.read_csv( 'H3070/acuracy.csv',header = None)
pd_acuracy['H3090'] = pd.read_csv( 'H3090/acuracy.csv',header = None)
pd_acuracy['H5010'] = pd.read_csv( 'H5010/acuracy.csv',header = None)
pd_acuracy['H5030'] = pd.read_csv( 'H5030/acuracy.csv',header = None)
pd_acuracy['H5050'] = pd.read_csv( 'H5050/acuracy.csv',header = None)
pd_acuracy['H5070'] = pd.read_csv( 'H5070/acuracy.csv',header = None)
pd_acuracy['H5090'] = pd.read_csv( 'H5090/acuracy.csv',header = None)
pd_acuracy['H9010'] = pd.read_csv( 'H9010/acuracy.csv',header = None)
pd_acuracy['H9030'] = pd.read_csv( 'H9030/acuracy.csv',header = None)
pd_acuracy['H9050'] = pd.read_csv( 'H9050/acuracy.csv',header = None)
pd_acuracy['H9070'] = pd.read_csv( 'H9070/acuracy.csv',header = None)
pd_acuracy['H9090'] = pd.read_csv( 'H9090/acuracy.csv',header = None)
#print(pd_acuracy)
np.savetxt("acuracy_marged.csv", pd_acuracy.values , delimiter=",")


pd_testing_loss = pd.read_csv( 'H1010/testing_loss.csv', header = None, names = ('H'))
pd_testing_loss['H1030'] = pd.read_csv( 'H1030/testing_loss.csv',header = None)
pd_testing_loss['H1050'] = pd.read_csv( 'H1050/testing_loss.csv',header = None)
pd_testing_loss['H1070'] = pd.read_csv( 'H1070/testing_loss.csv',header = None)
pd_testing_loss['H1090'] = pd.read_csv( 'H1090/testing_loss.csv',header = None)
pd_testing_loss['H3010'] = pd.read_csv( 'H3010/testing_loss.csv',header = None)
pd_testing_loss['H3030'] = pd.read_csv( 'H3030/testing_loss.csv',header = None)
pd_testing_loss['H3050'] = pd.read_csv( 'H3050/testing_loss.csv',header = None)
pd_testing_loss['H3070'] = pd.read_csv( 'H3070/testing_loss.csv',header = None)
pd_testing_loss['H3090'] = pd.read_csv( 'H3090/testing_loss.csv',header = None)
pd_testing_loss['H5010'] = pd.read_csv( 'H5010/testing_loss.csv',header = None)
pd_testing_loss['H5030'] = pd.read_csv( 'H5030/testing_loss.csv',header = None)
pd_testing_loss['H5050'] = pd.read_csv( 'H5050/testing_loss.csv',header = None)
pd_testing_loss['H5070'] = pd.read_csv( 'H5070/testing_loss.csv',header = None)
pd_testing_loss['H5090'] = pd.read_csv( 'H5090/testing_loss.csv',header = None)
pd_testing_loss['H9010'] = pd.read_csv( 'H9010/testing_loss.csv',header = None)
pd_testing_loss['H9030'] = pd.read_csv( 'H9030/testing_loss.csv',header = None)
pd_testing_loss['H9050'] = pd.read_csv( 'H9050/testing_loss.csv',header = None)
pd_testing_loss['H9070'] = pd.read_csv( 'H9070/testing_loss.csv',header = None)
pd_testing_loss['H9090'] = pd.read_csv( 'H9090/testing_loss.csv',header = None)
#print(pd_testing_loss)
np.savetxt("testing_loss_marged.csv", pd_testing_loss.values , delimiter=",")

pd_profit = pd.read_csv( 'H1010/profit.csv', header = None, names = ('H'))
pd_profit['H1030'] = pd.read_csv( 'H1030/profit.csv',header = None)
pd_profit['H1050'] = pd.read_csv( 'H1050/profit.csv',header = None)
pd_profit['H1070'] = pd.read_csv( 'H1070/profit.csv',header = None)
pd_profit['H1090'] = pd.read_csv( 'H1090/profit.csv',header = None)
pd_profit['H3010'] = pd.read_csv( 'H3010/profit.csv',header = None)
pd_profit['H3030'] = pd.read_csv( 'H3030/profit.csv',header = None)
pd_profit['H3050'] = pd.read_csv( 'H3050/profit.csv',header = None)
pd_profit['H3070'] = pd.read_csv( 'H3070/profit.csv',header = None)
pd_profit['H3090'] = pd.read_csv( 'H3090/profit.csv',header = None)
pd_profit['H5010'] = pd.read_csv( 'H5010/profit.csv',header = None)
pd_profit['H5030'] = pd.read_csv( 'H5030/profit.csv',header = None)
pd_profit['H5050'] = pd.read_csv( 'H5050/profit.csv',header = None)
pd_profit['H5070'] = pd.read_csv( 'H5070/profit.csv',header = None)
pd_profit['H5090'] = pd.read_csv( 'H5090/profit.csv',header = None)
pd_profit['H9010'] = pd.read_csv( 'H9010/profit.csv',header = None)
pd_profit['H9030'] = pd.read_csv( 'H9030/profit.csv',header = None)
pd_profit['H9050'] = pd.read_csv( 'H9050/profit.csv',header = None)
pd_profit['H9070'] = pd.read_csv( 'H9070/profit.csv',header = None)
pd_profit['H9090'] = pd.read_csv( 'H9090/profit.csv',header = None)
#print(pd_profit)
np.savetxt("profit_marged.csv", pd_profit.values , delimiter=",")
